### ISSUE TITLE
unknown keyword: :allow_retry

### ISSUE THREAD

**Issue by AlexisMunozC** [OLIOEX/janus-ar#47]
Hi, I am trying to use your gem, and when I start the server and reload the page I get this error:

![image](https://github.com/user-attachments/assets/b0ce1e47-bf9e-442c-90a5-2ddd29dce7f4)
![image](https://github.com/user-attachments/assets/5b79c6b5-a967-43b2-aa46-5eeadc970571)

It looks your passing a parameter that is not allowed. I am using rails 7.2.1 with ruby 3.2.2

```ArgumentError (unknown keyword: :allow_retry):
17:54:49 web.1  |   
17:54:49 web.1  | janus-ar (7.2.0) lib/janus-ar/active_record/connection_adapters/janus_mysql2_adapter.rb:82:in `execute_and_free'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/connection_adapters/mysql2/database_statements.rb:18:in `internal_exec_query'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:114:in `query'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:110:in `query_values'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/connection_adapters/abstract/schema_statements.rb:60:in `table_exists?'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/schema_migration.rb:54:in `block in create_table'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:395:in `with_connection'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/schema_migration.rb:53:in `create_table'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:1434:in `initialize'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:1282:in `new'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:1282:in `open'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:776:in `block (2 levels) in pending_migrations'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration/pending_migration_connection.rb:8:in `with_temporary_pool'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:775:in `block in pending_migrations'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:774:in `each'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:774:in `pending_migrations'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:753:in `check_pending_migrations'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:663:in `block (2 levels) in call'
17:54:49 web.1  | activesupport (7.2.1) lib/active_support/file_update_checker.rb:85:in `execute'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:668:in `block in call'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:660:in `synchronize'
17:54:49 web.1  | activerecord (7.2.1) lib/active_record/migration.rb:660:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
17:54:49 web.1  | activesupport (7.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:30:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
17:54:49 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
17:54:49 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
17:54:49 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
17:54:49 web.1  | web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
17:54:49 web.1  | railties (7.2.1) lib/rails/rack/logger.rb:41:in `call_app'
17:54:49 web.1  | railties (7.2.1) lib/rails/rack/logger.rb:29:in `call'
17:54:49 web.1  | sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/request_id.rb:33:in `call'
17:54:49 web.1  | rack (3.1.7) lib/rack/method_override.rb:28:in `call'
17:54:49 web.1  | rack (3.1.7) lib/rack/runtime.rb:24:in `call'
17:54:49 web.1  | activesupport (7.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/static.rb:27:in `call'
17:54:49 web.1  | rack (3.1.7) lib/rack/sendfile.rb:114:in `call'
17:54:49 web.1  | actionpack (7.2.1) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
17:54:49 web.1  | rack-cors (2.0.2) lib/rack/cors.rb:102:in `call'
17:54:49 web.1  | railties (7.2.1) lib/rails/engine.rb:535:in `call'
17:54:49 web.1  | puma (6.4.3) lib/puma/configuration.rb:272:in `call'
17:54:49 web.1  | puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'
17:54:49 web.1  | puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
17:54:49 web.1  | puma (6.4.3) lib/puma/request.rb:99:in `handle_request'
17:54:49 web.1  | puma (6.4.3) lib/puma/server.rb:464:in `process_client'
17:54:49 web.1  | puma (6.4.3) lib/puma/server.rb:245:in `block in run'
17:54:49 web.1  | puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'```

**Comment by lloydwatkin** [comment]
Hello @AlexisMunozC, what version of the GEM are you using?

**Comment by AlexisMunozC** [comment]
> Hello @AlexisMunozC, what version of the GEM are you using?

Hi, the version is 7.2.0
![image](https://github.com/user-attachments/assets/db054b66-6c62-45e0-92e6-653236462c5e)

**Comment by lloydwatkin** [comment]
We haven't hit this issue on our systems, would you be able to provide a test case and I'll get it fixed ASAP. Thanks!

**Comment by lloydwatkin** [comment]
Closing due to inactivity. If you want to continue the conversation please reopen!

**Comment by nguyenngoc2505** [comment]
@lloydwatkin I've same issue. I've using activerecord (7.2.2.1), I found that activerecord 7.2.2.1 passes the allow_retry key as a variable but janus-ar (7.2.0) doesn't receive this variable so it causes an error.

https://github.com/rails/rails/blob/fb6c4305939da06efdf2893d99130e7829c53e8b/activerecord/lib/active_record/connection_adapters/mysql2/database_statements.rb#L18

https://github.com/OLIOEX/janus-ar/blob/main/lib/janus-ar/active_record/connection_adapters/janus_mysql2_adapter.rb#L83

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/f31e45f2-1076-47e0-b0a2-1893cabbcc89" />

**Comment by lloydwatkin** [comment]
Published at v7.2.1. Let me know if the problem persists!

**Comment by nguyenngoc2505** [comment]
@lloydwatkin Thanks for the quick fixing, But I've another error. 

https://github.com/OLIOEX/janus-ar/blob/main/lib/janus-ar/active_record/connection_adapters/janus_mysql2_adapter.rb#L130-L132

https://github.com/rails/rails/blob/v7.2.0/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L113-L115

I think `replica_connection.execute(sql)` return mysql result not ActiveRecord::Result so may we need to change execute to `exec_query`. I've try and it worked

<img width="801" alt="Image" src="https://github.com/user-attachments/assets/a327e05f-a3c1-48a8-927e-6cc9709b5b93" />

**Comment by lloydwatkin** [comment]
@nguyenngoc2505 are you happy to put in a pull request? I'm not actively supporting rails 7 as we've moved on. If you can please base your change off the v7.2.1 tag 👍
